# Google OAuth Credentials
# Get credentials from: https://console.cloud.google.com/

# Google OAuth Configuration
google.client.id=
google.client.secret=
google.callback.url=
google.scope=https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile