security.super_admin.username=admin
security.super_admin.password_bcrypt=$2a$12$UllaLd399u9rzzFCvwLK8Of5vL1l9MxyC1OCMR1cyfCd4jxoyBqf2
security.super_admin.role_code=SUPER_ADMIN
security.system_ghost.user_id=1
security.system_ghost.display_name=SYSTEM
